
package GUI;

import javax.media.j3d.Canvas3D;
import Model.Universo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author fvelasco
 */
public class ControlWindow extends JFrame {
  private Universo universe;
   private Visualization cambiaVistas;
   ArrayList<Canvas3D> canvass;
  public ControlWindow(ArrayList<Canvas3D> canvas, Universo anUniverse) {
    super();
    universe = anUniverse;
    initComponents();
    //setLocation (920, 100);
    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        closeApp(0);
      }
    });
    setLocation(1400,100);
    canvass = canvas;
    Visualization visualization = new Visualization (this, false, canvas.get(2));
    visualization.setVisible(true);
    cambiaVistas= new Visualization (this, false, canvas.get(0));
    cambiaVistas.setLocation(750,100);
    cambiaVistas.setVisible(true);
    pack();
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primitiveGroup = new javax.swing.ButtonGroup();
        appearanceGroup = new javax.swing.ButtonGroup();
        panelVistas = new javax.swing.JPanel();
        libre = new javax.swing.JRadioButton();
        tierra = new javax.swing.JRadioButton();
        nave = new javax.swing.JRadioButton();
        commandsPanel = new javax.swing.JPanel();
        exitApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control");
        setMinimumSize(new java.awt.Dimension(300, 345));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        panelVistas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vistas"));
        panelVistas.setName("Vistas"); // NOI18N
        panelVistas.setLayout(new java.awt.GridLayout(2, 0));

        primitiveGroup.add(libre);
        libre.setSelected(true);
        libre.setText("Libre");
        libre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libreActionPerformed(evt);
            }
        });
        panelVistas.add(libre);

        primitiveGroup.add(tierra);
        tierra.setText("Tierra");
        tierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tierraActionPerformed(evt);
            }
        });
        panelVistas.add(tierra);

        primitiveGroup.add(nave);
        nave.setText("Nave");
        nave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naveActionPerformed(evt);
            }
        });
        panelVistas.add(nave);

        getContentPane().add(panelVistas);

        commandsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        exitApp.setText("Salir");
        exitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppActionPerformed(evt);
            }
        });
        commandsPanel.add(exitApp);

        getContentPane().add(commandsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void exitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppActionPerformed
    // TODO add your handling code here:
    closeApp(0);
  }//GEN-LAST:event_exitAppActionPerformed

    private void libreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libreActionPerformed
        // TODO add your handling code here:
        cambiaVistas.setCanvas(canvass.get(0));
    }//GEN-LAST:event_libreActionPerformed

    private void tierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tierraActionPerformed
        // TODO add your handling code here:
        cambiaVistas.setCanvas(canvass.get(1));

    }//GEN-LAST:event_tierraActionPerformed

    private void naveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naveActionPerformed
        // TODO add your handling code here:
        cambiaVistas.setCanvas(canvass.get(3));

    }//GEN-LAST:event_naveActionPerformed

  public void showWindow () {
    setVisible (true);
  }

  void closeApp (int code) {
    universe.closeApp(code);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup appearanceGroup;
    private javax.swing.JPanel commandsPanel;
    private javax.swing.JButton exitApp;
    private javax.swing.JRadioButton libre;
    private javax.swing.JRadioButton nave;
    private javax.swing.JPanel panelVistas;
    private javax.swing.ButtonGroup primitiveGroup;
    private javax.swing.JRadioButton tierra;
    // End of variables declaration//GEN-END:variables
}
